import Head from "next/head";
import { HomePageSearch } from "../components/HomePageSearch";
import { MultipleSelect } from "../components/MultipleSelect";
import Tabovi from "../components/navigation/Tabovi";

const brend = [
  { label: "Audi", value: "1" },
  { label: "Alfa Romeo", value: "2" },
  { label: "Abarth", value: "3" },
  { label: "BMW", value: "4" },
  { label: "Daewoo", value: "5", disabled: true },
  { label: "Dodge", value: "6" },
  { label: "Dacia", value: "7" },
  { label: "Lada", value: "8" },
  { label: "Fiat", value: "9" },
];
const model = [
  { label: "Audi", value: "1" },
  { label: "Alfa Romeo", value: "2" },
  { label: "Abarth", value: "3" },
  { label: "BMW", value: "4" },
  { label: "Daewoo", value: "5", disabled: true },
  { label: "Dodge", value: "6" },
  { label: "Dacia", value: "7" },
  { label: "Lada", value: "8" },
  { label: "Fiat", value: "9" },
];
const stanje = [
  { label: "Novo", value: "1" },
  { label: "Polovno", value: "2" },
  { label: "Osteceno", value: "3" },
];

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto my-3">
        <div
          className="bg-blue-300/10 p-10 my-3 bg-cover rounded-md shadow-sm"
          style={{
            backgroundImage:
              "url(https://img.freepik.com/free-photo/red-sport-car-front-side-view-black-wheel-with-metallic-silver-color_114579-1160.jpg?w=1380&t=st=1660924252~exp=1660924852~hmac=636ca62f5caa137fd9e85ab7327b50b029cbf4053b7cf7dd2bc2c67704e284ec)",
          }}
        >
          <HomePageSearch />
        </div>
      </div>
    </div>
  );
}
